15. Migration Operations/HelloCoreMvcApp/HelloCoreMvcApp/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Db_Context.DatabaseContext;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;

namespace HelloCoreMvcApp.Controllers
{
    public class CustomerController : Controller
    {
        public IActionResult Create()
        {
            ViewBag.AddressList = AddressList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Customer aCustomer)
        {
            if (ModelState.IsValid)
            {
                CoreDb db = new CoreDb();
                db.Customers.Add(aCustomer);
                bool isSaved = db.SaveChanges() > 0;

                if(isSaved)
                    return RedirectToAction("Details", aCustomer);
                else
                    return ViewBag.ErrorMessage = "Customer not saved!";
            }                      
            else
            {
                ViewBag.AddressList = AddressList();
                return View(aCustomer);
            }                     
        }

        public IActionResult Details(Customer aCustomer)
        {
            ViewBag.Customer = aCustomer;
            return View();
        }

        public List<SelectListItem> AddressList()
        {
            List<SelectListItem> address = new List<SelectListItem>()
            {
                new SelectListItem { Value = "DHK", Text = "Dhaka"},
                new SelectListItem { Value = "CTG", Text = "Chittagong"},
                new SelectListItem { Value = "Lax", Text = "Lakshmipur"},
            };

            return address;
        }
    }
}

15. Migration Operations/HelloCoreMvcApp/HelloCoreMvcApp/Views/Customer/Create.cshtml
@using Models
@model Customer
@{
    Layout = "_DashboardLayout";
}

<h4>Create Customer</h4>
<form method="post" asp-action="Create" asp-controller="Customer">
    <div class="form-group">
        <label for="Name" class="col-md-2 control-lable">Name</label>
        <div class="col-md-10">
            <input type="text" asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label for="Address" class="col-md-2 control-lable">Address</label>
        <div class="col-md-10">
            <select asp-for="Address" asp-items="@ViewBag.AddressList" class="form-control">
                <option value="">-- Select Address --</option>
            </select>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <span class="text-danger">@ViewBag.ErrorMessage</span>
        </div>
    </div>
</form>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>